### ISSUE TITLE
apisix-ingress-controller-PodInitializing

### ISSUE THREAD

**Issue by wjkhappy14** [apache/apisix-helm-chart#240]
when run  command:
helm install apisix-ingress-controller apisix/apisix-ingress-controller

then got  this log:
container "apisix-ingress-controller" in pod "apisix-ingress-controller-7859756884-jqnzk" is waiting to start: PodInitializing

**Comment by wjkhappy14** [comment]
K8S reason:
ContainersNotInitialized
containers with incomplete status: [wait-apisix-admin]

**Comment by wjkhappy14** [comment]
Container image "busybox:1.28" already present on machine

**Comment by tao12345666333** [comment]
you should run this command:

```
helm install apisix apisix/apisix --set gateway.type=NodePort --set ingress-controller.enabled=true --set ingress-controller.config.apisix.serviceNamespace=apisix --namespace apisix --create-namespace --set ingress-controller.config.apisix.serviceName=apisix-admin
```

 `ingress-controller.config.apisix.serviceName=apisix-admin` and   `ingress-controller.config.apisix.serviceNamespace=apisix`  are the root cause. 

https://github.com/apache/apisix-helm-chart/blob/2a481404fc85707283df1ce0eda0e6680240d58a/charts/apisix-ingress-controller/templates/deployment.yaml#L51-L54

**Comment by wjkhappy14** [comment]
now i run the command as you said, all pos and service  are going well 
thks so much
