### ISSUE TITLE
Problem with Release: Packaged .tgz does not contain correct dependency

### ISSUE THREAD

**Issue by dangllucas** [apache/apisix-helm-chart#317]
Hey there,

when comparing the Release 0.10.1 with 0.10.1 you find in the diff a the commit #15a838c of PR #309 (https://github.com/apache/apisix-helm-chart/pull/309)

These changes are reflected in the Master Branch and also in the source of the Release 0.10.1 (https://github.com/apache/apisix-helm-chart/releases/tag/apisix-0.10.1)

But when looking at the Packaged Helm Chart Archive you find the differences:
![image](https://user-images.githubusercontent.com/27855488/181230819-ddcf17e5-f911-4bf3-adc3-8542208a20f5.png)

Left from Source Code zip | Right from Packaged Helm Chart 

This makes using the apisix Chart with the Dashboard exposed with Ingress currently unusable.

**Comment by tokers** [comment]
@tao12345666333

**Comment by tao12345666333** [comment]
Hi, it's all correct. 0.10.1 is just to update APISIX Ingress dependencies.

In fact, you can't see actual changes by comparing tags directly.
Because each Helm chart is released independently


If you want this feature to appear in a new Helm chart, we should do a new release for apisix-dashboard, then update the dependencies in APISIX’ s chart. 

You can create a new PR for this. Thanks
