### ISSUE TITLE
Invalid Semantic Version

### ISSUE THREAD

**Issue by dcuebas** [apache/apisix-helm-chart#393]
I am using an image that includes my custom external plugin but because of 
(`.../apisix/templates/configmap.yaml` - line 17)

`{{- $isBeta := (semverCompare ">=2.99.0-0" .Values.apisix.image.tag) }}` 

I now get an error:
`error calling semverCompare: Invalid Semantic Version`

Please consider users who are not using default apisix images.

**Comment by tokers** [comment]
What's the APISIX version are you using?

**Comment by dcuebas** [comment]
2.15.0

**Comment by tao12345666333** [comment]
what's your image tag?

**Comment by dcuebas** [comment]
It is a custom image - hence no semantic version tag.

**Comment by tao12345666333** [comment]
This is where the problem lies.

The logic here exists for APISIX 3.0-compatible mirroring to run.
We will publish an official Helm chart for 3.0 once other relevant components are in place.
At that time, these logics will be removed.


What you need to do is to remove this part of the logic, or modify your image tag.
