### ISSUE TITLE
How deploy v3.1 in standalone mode? 

### ISSUE THREAD

**Issue by caibirdme** [apache/apisix-helm-chart#472]
For gitops, we'd love to run apisix in standalone mode, but cannot find any docs for that.

**Comment by igor-borisoglebski** [comment]
This should have you covered: [Latest (currently 3.1) APISIX Stand-alone mode documentation](https://apisix.apache.org/docs/apisix/stand-alone/)

**Comment by flylan** [comment]
> This should have you covered: [Latest (currently 3.1) APISIX Stand-alone mode documentation](https://apisix.apache.org/docs/apisix/stand-alone/)

Your link is invalid, this link is the correct one：https://apisix.apache.org/docs/apisix/3.1/stand-alone/

**Comment by flylan** [comment]
The document directory structure of Apisix is a bit unfriendly, and latest versions documents should not default to hiding version numbers. Currently, only historical versions will display version numbers

Because if the current latest version becomes a historical version, there may be situations where document links cannot be accessed

![image](https://user-images.githubusercontent.com/12097229/233016742-2a31b23d-4d42-4103-b1bb-cd50e726290e.png)
![image](https://user-images.githubusercontent.com/12097229/233016794-b73bb311-a399-44b9-9da1-683de5ab9552.png)

**Comment by nagidocs** [comment]
The current helm-chart does only support `config_provider: **control_plane**` for `deployment.role "data_plane"`
As I can see here, https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/configmap.yaml#L370C1-L371C1

How we can config it have `config_provider: **yaml**` through this helm-chart for the role **data_plane**, any idea?
It's seems it's not yet supported!

**Comment by gigi206** [comment]
Same issue, the helm chart seems buggy, impossible to specify `role_data_plane.config_provider: yaml` for data_plane role `role: data_plane` because it's hardcoded here
https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/configmap.yaml#L312

**Comment by Revolyssup** [comment]
Currently when the role is `data_plane`, config_provider is hardcoded as `etcd` so standalone mode can't be used. The solution can be to add a configuration option in values.yaml like `.Values.deployment.standalone` which when set to true then config_provider will be set as `yaml` for standalone mode instead of etcd.
