### ISSUE TITLE
feat: update helm chart to talk about CP/DP separation deployment of APISIX

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix-helm-chart#655]
### Description

By default, the DP and CP of the APISIX cluster are deployed in a pod. In this case, when the CP receives a large number of requests from the ingress controller, it will affect the pod's CPU.

I hope to talk about the DP/CP separation of APISIX cluster.

**Comment by Revolyssup** [comment]
I  see that this issue was originally created in apisix-ingress-controller but was later transferred. In context of ingress controller, from the release v1.7 we got rid of control plane anyways and ingress controller pod contains the apisix in data plane role only. So I don't think this is any longer relevant in context of the ingress controller.
For APISIX installation with helm chart, we already have the option to deploy control plane and data plane separately in decoupled mode. https://github.com/apache/apisix-helm-chart/pull/461
So is this issue still valid?
